### ISSUE TITLE
Filter out the Traffi Accidents, Traffic Violations samples, and Pedestrain Incidents

### ISSUE THREAD

**Issue by HarryHsing** [fesvhtr/CUVA#1]
Thank you very much for your amazing work!

I wonder given the cuva_gt_cleaned.json and cuva_test.json, how can I locate the samples with only Traffi Accidents, Traffic Violations samples, and Pedestrain Incidents? Are there any labels marking this?

Thank you very much for your support in adcanve!

Best,
Zhenghao

**Comment by Dulpy** [comment]
Thanks for the question, label marks have been updated in the category.txt

**Comment by HarryHsing** [comment]
> Thanks for the question, label marks have been updated in the category.txt

Hi, thanks for the reply! But it seems that category.txt is an empty file

**Comment by Dulpy** [comment]
Sorry, I have updated the category.txt. For your convenience, here is the Chinese version while annotating
![image-20230926173500240](https://github.com/fesvhtr/CUVA/assets/32271681/28caf476-8a6b-4c03-b3c0-90b4297a7edd)

**Comment by HarryHsing** [comment]
> Sorry, I have updated the category.txt. For your convenience, here is the Chinese version while annotating ![image-20230926173500240](https://private-user-images.githubusercontent.com/32271681/346249601-28caf476-8a6b-4c03-b3c0-90b4297a7edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNDYwMjgsIm5iZiI6MTcyMDI0NTcyOCwicGF0aCI6Ii8zMjI3MTY4MS8zNDYyNDk2MDEtMjhjYWY0NzYtOGE2Yi00YzAzLWIzYzAtOTBiNDI5N2E3ZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA2MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0Y2YzM2E4ZTFjZDMyNjhlYTNjNzQ4OWNkNWUyYWY1NGUxMmNjZGFkNjRkNzY2ZTI0M2Q2MmIzNWRhMDJjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zx8mNO3QPwRxSllWJ6t_vhatFhOXJpspd_jNSmfG304)

well noted! thank you very much for your prompt support!
