### ISSUE TITLE
About Voting_new.json

### ISSUE THREAD

**Issue by HarryHsing** [fesvhtr/CUVA#2]
Hi Hang Du, can you tell me what is Voting_new.json used for?

Thanks!

**Comment by Dulpy** [comment]
Sorry, where did you find this file?

**Comment by Dulpy** [comment]
Sorry, where did you find this file?

**Comment by HarryHsing** [comment]
> Sorry, where did you find this file?

From the dataset download i think. 
`  {
   "video_name": 1,
   "query": "stealing property",
   "answer": [
    87.0,
    115.0
   ]
  },`

**Comment by Dulpy** [comment]
It's for curve annotation. For your example, it means "stealing property" happens from "87"s to "115"s in video "1"
