### ISSUE TITLE
IndexError: index 976 is out of bounds for dimension 0 with size 662

### ISSUE THREAD

**Issue by happyrenxiaozhao** [fesvhtr/CUVA#3]
Hello, thank you for your work! I recently tried to reproduce your code, but the following error occurred:
IndexError: index 976 is out of bounds for dimension 0 with size 662

Here are some details I have, I hope you can help me out!
![截图 2024-08-19 20-52-39](https://github.com/user-attachments/assets/1fb85fe9-c46c-4d3d-9178-edc2aae67785)
![截图 2024-08-19 20-53-28](https://github.com/user-attachments/assets/7ccf709b-b749-43ef-bd29-d6df2ec34e86)

**Comment by happyrenxiaozhao** [comment]
@fesvhtr

**Comment by happyrenxiaozhao** [comment]
@fesvhtr  I debugged the code and found the place where the error was reported. In line 106 of the video_chat.py file, the value video_start_token_pos + num_patches + 1 exceeds the index range. How should I modify it?
我调试了代码，并且找到了报错的地方，在video_chat.py这个文件的106行，video_start_token_pos + num_patches + 1这个值超出了索引范围，我应该怎么进行修改呢？
![截图 2024-08-20 11-20-42](https://github.com/user-attachments/assets/83e30997-4be5-4291-93d3-f847f22cb846)

**Comment by Dulpy** [comment]
It seems that the errors happened during the concatenation of the video tokens and text tokens, 
Here are some suggestions for you to check:
1. Check the number of frames you extracted from the video
2. Check the ModelArguments: mm_use_vid_start_end
3. Check the video input, as we found that nearly 10 videos tested were not available.
And if it doesn't work, we will be releasing a new version of the model in the next few days, we'll be glad to invite you to try the new one.

**Comment by happyrenxiaozhao** [comment]
> It seems that the errors happened during the concatenation of the video tokens and text tokens, Here are some suggestions for you to check:
> 
> 1. Check the number of frames you extracted from the video
> 2. Check the ModelArguments: mm_use_vid_start_end
> 3. Check the video input, as we found that nearly 10 videos tested were not available, and we'll fix it in the next version
>    And if it doesn't work, we will be releasing a new version of the model in the next few days, we'll be glad to invite you to try the new one.

Thank you for your answer, I am very happy to look forward to your new version, and hope to receive your notice in time!

**Comment by Dulpy** [comment]
New version: https://github.com/[Dulpy/ECVA](https://github.com/Dulpy/ECVA
We're glad to invite you to try this GitHub repository.
